In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('sujo.xlsx', header=None, names=['Hora', 'Temperatura'])

df_limpo = df.dropna(subset=['Temperatura'])

print(df_limpo)

df_limpo.to_excel('limpo.xlsx', index=False)

          Hora  Temperatura
0         Hora  Temperatura
1     20:08:52        32.11
3     20:08:53        32.11
6     20:08:54        32.11
8     20:08:55        32.11
...        ...          ...
2816  20:31:21           30
2818  20:31:22         39.3
2820  20:31:23        39.41
2822  20:31:24        39.41
2824  20:31:25        39.41

[1397 rows x 2 columns]